// config.js
const API_CLASS_ENDPOINT = process.env.NEXT_PUBLIC_API_CLASS_ENDPOINT;
const API_MEDICINE_ENDPOINT = process.env.NEXT_PUBLIC_API_MEDICINE_ENDPOINT;

export { API_CLASS_ENDPOINT, API_MEDICINE_ENDPOINT };
